/*
  tổng độ chenh lệch của a[i] và a[i-1] ;
  sau mỗi bước cập nhập lại giá trị của a[i];
*/

#include <bits/stdc++.h>
 
using namespace std;
 
#define endl "\n"
#define faster() \
    ios_base::sync_with_stdio(0); \
    cin.tie(NULL); \
    cout.tie(NULL);
#define fi first
#define se second
#define INF 1e9
#define all(x) x.begin(),x.end()
#define pii pair<int,int>
typedef long long ll;
typedef double dbl;
 
const ll M = 1e9+7;
 
void solve(){
    string s;
    cin >> s;
    int ans = 1;
    int d = 1;
    for (int i=1;i<s.length();i++){
        if (s[i] == s[i-1]){
            ans = max(ans,++d);
        }else{
            d = 1;
        }
    }
    cout << ans;
}
 
int main(){
    faster();
    int t;
    t = 1;
    //cin >> t;
    //cin.ignore();
    while (t--){
        solve();
    }
    return 0;
}
// Triệu Ngọc Tâm _ Dynamite
//                                    .:^~!!7??JJJJYYYYJJJJ??7!!~^:.
//                               :^~7?JJYYYYYYYYYYYYYYYYYYYYYYYYYYJJ?7~^:
//                          .:~7JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7~:.
//                       .~7JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7~.
//                    .~?JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ?~.
//                 .^7JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7^.
//               .~JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ~.
//             .!JYYYYYYYYYYYYYYYYYYYYYYYYYYJYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ!.
//            ~JYYYYYYYYYYYYYYYYYYYYYJJYY!:.^~~!?Y7::^~~!7?~:::~~~!?JYYYYYYYYYYYYYYYYYYYYYJ~
//          ^?YYYYYYYYYYYYYYYYYYYYYYY^ ?YJ7~^^::^~!!7?Y?. .??^.:^:..^?JYYYYYYYYYYYYYYYYYYYYY?^
//         !YYYYYYYYYYYYYYYYYYYYYYYY?  7YYYYJ7~^~~: .!Y!  :!!!!~:.^!^  :7YYYYYYYYYYYYYYYYYYYYY!
//       .?YYYYYYYYYYYYYYYYYYYYYYYYY~   :7JYYJ77!~~~~!?7!~~~~~~7?!~~~~~~7?JJJYYYYYYYYYYYYYYYYYY?.
//      :JYYYYYYYYYYYYYYYYYYYYYYYYYY~.?7: .~J^                             ..:~!?YYYYYYYYYYYYYYYJ:
//     ^JYYYYYYYYYYYYYYYYYYYYYYYYYY!^7YYY?~:?.                                   :!JYYYYYYYYYYYYYJ^
//    :JYYYYYYYYYYYYYYYYYYYYYYYYYYY!. .!JYYY~                                      .7YYYYYYYYYYYYYJ:
//   .JYYYYYYYYYYYYYYYYYYYYYYYYYYY7:7?^  ^?J.                                        !YYYYYYYYYYYYYJ.
//   7YYYYYYYYYYYYYYYYYYYYYYYYYYYY: 75YJ!.~!           ~???????????777!~:             ?YYYYYYYYYYYYY7
//  ^YYYYYYYYYYYYYYYYYYYYYYYYYYYY7  .~?YYYJ:          .JYYYYYYYYYYYYYYYYY?.           ~YYYYYYYYYYYYYY^
//  ?YYYYYYYYYYYYYYYYYYYYYYYYYYYY~ !~. :!J7           ~YYYYYYYYYYYYYYYYYYY7           ^YYYYYYYYYYYYYY?
// ^YYYYYYYYYYYYYYYYYYYYYYYYYYYYJ!~JYJ7: ?^          .JYYYYYYYYYYYYYYYYYYY7           ~YYYYYYYYYYYYYYY^
// 7YYYYYYYYYYYYYYYYYYYYYYYYYYYY~  .7YYYJ?           ~YYYYYYYYYYYYYYYYYYYY^           ?YYYYYYYYYYYYYYY7
// ?YYYYYYYYYYYYYYYYYYYYYYYYYYYJ :?..JYYY^           ?YYYYYYYYYYYYYYYYYYJ^           ^YYYYYYYYYYYYYYYY?
// JYYYYYYYYYYYYYYYYYYYYYYYYYYY?. :.:YYYJ           ^YYYYYYYYYYYYYYYYJ?~.           .JYYYYYYYYYYYYYYYYJ
// YYYYYYYYYYYYYYYYYYYYYYYYYYYYJJ7^. ^7Y~           7JJJJJJJ????77!~^.             :JYYYYYYYYYYYYYYYYYY
// JYYYYYYYYYYYYYYYYYYYYYYYYYY7. .~7!..J.           .....                         ^JYYYYYYYYYYYYYYYYYYJ
// ?YYYYYYYYYYYYYYYYYYYYYYYYYJ. !~. ~JJ!                                        :7YYYYYYYYYYYYYYYYYYYY?
// 7YYYYYYYYYYYYYYYYYYYYYYYYYJ..JYY~ !Y:                                     :~?YYYYYYYYYYYYYYYYYYYYYY7
// ^YYYYYYYYYYYYYYYYYYYYYYYYYY?. ~?7 ^7                               ..:^~7?YYYYYYYYYYYYYYYYYYYYYYYYY^
//  ?YYYYYYYYYYYYYYYYYYYYYYYJ^^!~.  .?^          .!!!!!!!!!!!!!!!777??JJYYYYYYYYYYYYYYYYYYYYYYYYYYYYY?
//  ^YYYYYYYYYYYYYYYYYYYYYYY^ . !J77J?           ^YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY^
//   7YYYYYYYYYYYYYYYYYYYYY? :J: ..:J^           ?YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY7
//   .JYYYYYYYYYYYYYYYYYYYY?: . :!~~?           :YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ.
//    :JYYYYYYYYYYYYYYYYYYY777~. ^7Y~           7YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ:
//     ^JYYYYYYYYYYYYYYYYY!  .!J!:.J.          :YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ^
//      :JYYYYYYYYYYYYYYYJ..?^ ?YYJ!           !YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ:
//       .?YYYYYYYYYYYYYYJ: ...JYYY:          .JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY?.
//         !YYYYYYYYYYYYYYY?~. :7Y7           ~YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY!
//          ^?YYYYYYYYYYYYYYYJ!: ?:           JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY?^
//            ~JYYYYYYYYYYYYYYYYJJ^^^^^^^^^^^!YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ~
//             .!JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ!.
//               .~JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ~.
//                 .^7JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7^.
//                    .~?JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ?~.
//                       .~7JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7~.
//                          .:~7JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7~:.
//                               :^~7?JJYYYYYYYYYYYYYYYYYYYYYYYYYYJJ?7~^:
//                                    .:^~!!7??JJJJYYYYJJJJ??7!!~^:.
